name: STITest
favicon: null
layout_spectrum: 0.41799
typography_spectrum: 0.41445
title: Streeter Tech
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#020202'
    - '#ababab'
    - '#00719d'
    - '#20adda'
  brandStrength: 0.29632209008559585
  lightness: 0.6562187657691538
  saturation: 0.4436664544045925
  rhythmicContrast: 0.5
purpose: []
